### ISSUE TITLE
A bit more epic: Method injection for actions

### ISSUE THREAD

**Issue by atrauzzi** [atrauzzi/protoculture-hapi#10]
Rather than providing the hapi environment and the route configuration, controller actions could be targets for injection:

 - [ ] Reflect on action signature
 - [ ] Create a base `Request` class with a standard constructor
   - [ ] Boot a child container per request, instantiate and bind the desired `Request` class as per the signature
   - [ ] Do a pre-call phase to run validation against the current request via joi?
 - [ ] Look up and provide other injections requested
 - [ ] Named routes
   - [ ] Generate URIs to routes (not built into the framework)
